import { useRef, useState } from "react";
import { motion, useInView, AnimatePresence } from "motion/react";
import { Plus, Minus } from "lucide-react";

const faqs = [
  {
    question: "How does PBD make money?",
    answer:
      "PBD receives a small percentage of vendor rebates generated through the program. There are no membership fees or royalties.",
  },
  {
    question: "How do retailers receive rebates?",
    answer:
      "Vendor rebates are collected by PBD and paid to the store based on participation in approved programs and promotion sales. Tobacco is paid monthly. Core-mark, Beverage, FarmerBrothers is paid quarterly. Other program payments are Semi-Annual or Annually based on Vendor Agreements and payments.",
    note:
      "*Payments are highly dependent on vendors providing timely, accurate tracking, sales data, as well as payments.",
  },
  {
    question: "What does the retailer need to do?",
    answer:
      "Sign up! PBD manages vendor programs, merchandising support, and promotional execution so store owners can focus on running their business. All the retailer needs to do is update the promotional prices in the register.",
  },
  {
    question: "What is the cost to join PBD?",
    answer:
      "There is zero cost to join PBD. No membership fees, no royalties. PBD earns only when you earn—through a small share of vendor rebates generated by the program.",
  },
];

function FAQItem({
  faq,
  index,
  isOpen,
  onToggle,
  isInView,
}: {
  faq: (typeof faqs)[0];
  index: number;
  isOpen: boolean;
  onToggle: () => void;
  isInView: boolean;
}) {
  return (
    <motion.div
      className="border-b border-[#E0E0E0]"
      initial={{ opacity: 0, y: 20 }}
      animate={isInView ? { opacity: 1, y: 0 } : {}}
      transition={{
        duration: 0.5,
        delay: 0.2 + index * 0.1,
        ease: "easeOut",
      }}
    >
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between py-6 text-left group cursor-pointer"
      >
        <span
          className="text-[#0a0a0a] pr-8"
          style={{
            fontSize: "clamp(0.9375rem, 1.4vw, 1.125rem)",
            fontWeight: 400,
            letterSpacing: "-0.01em",
            lineHeight: 1.4,
          }}
        >
          {faq.question}
        </span>
        <span className="shrink-0 w-8 h-8 flex items-center justify-center border border-[#E0E0E0] text-[#111642] group-hover:border-[#111642] transition-colors">
          {isOpen ? <Minus size={14} /> : <Plus size={14} />}
        </span>
      </button>

      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.35, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <div className="pb-6 pr-12">
              <p
                className="text-[#555]"
                style={{
                  fontSize: "16px",
                  fontWeight: 400,
                  lineHeight: 1.7,
                }}
              >
                {faq.answer}
              </p>
              {faq.note && (
                <p
                  className="text-[#888] mt-3"
                  style={{
                    fontSize: "14px",
                    fontWeight: 400,
                    lineHeight: 1.6,
                    fontStyle: "italic",
                  }}
                >
                  {faq.note}
                </p>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

export function FAQSection() {
  const sectionRef = useRef<HTMLElement>(null);
  const isInView = useInView(sectionRef, { once: true, margin: "-80px" });
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section
      ref={sectionRef}
      className="bg-[#FFFFFF]"
      style={{ fontFamily: "'Inter', sans-serif", padding: "80px 0" }}
    >
      <div className="max-w-[1440px] mx-auto px-6 md:px-10 lg:px-[80px]">
        {/* Section Label */}
        <p
          className="text-[#999] uppercase tracking-[0.15em] mb-[56px]"
          style={{ fontSize: "11.2px", fontWeight: 500 }}
        >
          FAQ
        </p>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16">
          {/* Left: Headline + subtext */}
          <div className="flex flex-col gap-6">
            <motion.h2
              className="text-[#0a0a0a] max-w-[420px]"
              style={{
                fontSize: "clamp(32px, 4vw, 48px)",
                fontWeight: 400,
                lineHeight: 1.1,
                letterSpacing: "-0.03em",
              }}
              initial={{ opacity: 0, y: 30 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.7, ease: "easeOut" }}
            >
              Frequently asked questions.
            </motion.h2>

            <motion.p
              className="text-[#555] max-w-[360px]"
              style={{ fontSize: "16px", fontWeight: 400, lineHeight: 1.7 }}
              initial={{ opacity: 0, y: 20 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.7, delay: 0.15, ease: "easeOut" }}
            >
              Everything you need to know about joining the PBD network and how the program works.
            </motion.p>
          </div>

          {/* Right: Accordion */}
          <div className="border-t border-[#E0E0E0]">
            {faqs.map((faq, index) => (
              <FAQItem
                key={faq.question}
                faq={faq}
                index={index}
                isOpen={openIndex === index}
                onToggle={() =>
                  setOpenIndex(openIndex === index ? null : index)
                }
                isInView={isInView}
              />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
